lsi: false
highlighter: rouge

url:                 https://texus.me
permalink:           pretty
paginate:            10

excerpt_separator: <!--more-->

plugins:
  - jekyll-sitemap
  - jekyll-paginate
