lsi: false
highlighter: pygments

url:                 https://texus.me
permalink:           pretty
relative_permalinks: true
paginate:            10

excerpt_separator: <!--more-->

gems:
  - jekyll-sitemap
