lsi: false
highlighter: pygments

url:                 https://texus.me
permalink:           pretty
paginate:            10

excerpt_separator: <!--more-->

gems:
  - jekyll-sitemap
  - jekyll-paginate
